#!/usr/bin/env bash
# Deploy Strongbox end to end.
#
#   ./scripts/deploy.sh you@example.com [stack-name] [region]
#
# Requires: aws cli v2, sam cli, an authenticated AWS session.

set -euo pipefail

EMAIL="${1:-}"
STACK="${2:-strongbox}"
REGION="${3:-$(aws configure get region || echo eu-west-1)}"

if [[ -z "$EMAIL" ]]; then
  echo "Usage: $0 <notification-email> [stack-name] [region]" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

echo "==> Building"
sam build

echo "==> Deploying stack '$STACK' to $REGION"
sam deploy \
  --stack-name "$STACK" \
  --region "$REGION" \
  --capabilities CAPABILITY_IAM \
  --resolve-s3 \
  --no-confirm-changeset \
  --no-fail-on-empty-changeset \
  --parameter-overrides "ProjectName=$STACK" "NotifyEmail=$EMAIL"

echo "==> Reading stack outputs"
outputs=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" --region "$REGION" \
  --query 'Stacks[0].Outputs' --output json)

get() { echo "$outputs" | python3 -c "import json,sys;print(next(o['OutputValue'] for o in json.load(sys.stdin) if o['OutputKey']=='$1'))"; }

API_URL=$(get ApiBaseUrl)
CLIENT_ID=$(get UserPoolClientId)
WEB_BUCKET=$(get WebBucketName)
DIST_ID=$(get DistributionId)
SITE_URL=$(get SiteUrl)

echo "==> Writing web/config.js"
cat > web/config.js <<EOF
/* Generated by scripts/deploy.sh - do not edit by hand. */
window.STRONGBOX_CONFIG = {
  region: "$REGION",
  userPoolClientId: "$CLIENT_ID",
  apiBaseUrl: "$API_URL"
};
EOF

echo "==> Publishing web app to s3://$WEB_BUCKET"
aws s3 sync web/ "s3://$WEB_BUCKET/" --region "$REGION" --delete \
  --cache-control "public,max-age=300"
aws s3 cp web/config.js "s3://$WEB_BUCKET/config.js" --region "$REGION" \
  --cache-control "no-cache"

echo "==> Invalidating CloudFront cache"
aws cloudfront create-invalidation \
  --distribution-id "$DIST_ID" --paths "/*" \
  --query 'Invalidation.Id' --output text >/dev/null

cat <<EOF

Done.

  Site   $SITE_URL
  API    $API_URL

Confirm the SNS subscription in $EMAIL before demoing, or upload
notifications will not arrive. CloudFront takes a few minutes to
finish propagating on a first deploy.
EOF
