/* Generated by scripts/deploy.sh from the CloudFormation stack outputs.
   The values below are placeholders so the page loads locally. */
window.STRONGBOX_CONFIG = {
  region: "REPLACE_REGION",
  userPoolClientId: "REPLACE_CLIENT_ID",
  apiBaseUrl: "REPLACE_API_URL"
};
